# Generated by Django 4.2.10 on 2026-03-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('modality', models.CharField(choices=[('per_ton', 'Por Tonelada'), ('lease', 'Arrendamento (diárias)')], max_length=32)),
                ('tons', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rate_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.vehicle')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
            },
        ),
    ]
