# Generated by Django 4.2.10 on 2026-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='expense_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
