# Generated by Django 4.2.10 on 2026-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_trip_expense_value_trip_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='base_expense_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
