# Generated by Django 4.2.10 on 2026-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_trip_base_expense_value_trip_driver_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='final_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_expense_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='initial_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
