# Generated by Django 4.2.10 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_trip_final_km_trip_fuel_expense_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em curso'), ('completed', 'Encerrada')], default='in_progress', max_length=20),
        ),
    ]
