# Generated by Django 4.2.10 on 2026-03-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='progress_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movement_type', models.CharField(choices=[('expense', 'Gasto'), ('revenue', 'Recebimento')], max_length=20)),
                ('expense_category', models.CharField(blank=True, choices=[('fuel', 'Combustível'), ('other', 'Outros gastos')], default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='transport.trip')),
            ],
            options={
                'verbose_name': 'Lançamento da Viagem',
                'verbose_name_plural': 'Lançamentos da Viagem',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
