# Generated by Django 4.2.10 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_trip_dates_progress_tripmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmovement',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
