# Generated by Django 4.2.10 on 2026-03-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_module_investments',
            field=models.BooleanField(default=False, verbose_name='Módulo Investimentos'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_module_transport',
            field=models.BooleanField(default=False, verbose_name='Módulo Transportadora'),
        ),
    ]
