# Generated by Django 4.2.10 on 2026-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_has_module_investments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, verbose_name='Admin da Plataforma'),
        ),
    ]
