# Generated by Django 4.2.10 on 2026-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_platform_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Gerente'), ('operator', 'Operador')], default='operator', max_length=16, verbose_name='Papel'),
        ),
    ]
