# Generated by Django 4.2.10 on 2026-03-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('transport', 'Transportadora'), ('investments', 'Investimentos')], max_length=32)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Parâmetro do Tenant',
                'verbose_name_plural': 'Parâmetros do Tenant',
                'ordering': ['module', 'key'],
                'unique_together': {('tenant', 'module', 'key')},
            },
        ),
    ]
