# Generated by Django 4.2.10 on 2026-03-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenantauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantparameter',
            name='module',
            field=models.CharField(choices=[('general', 'Geral'), ('transport', 'Transportadora'), ('investments', 'Investimentos')], max_length=32),
        ),
    ]
