# Generated by Django 4.2.10 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tenantparameter_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantparameter',
            name='module',
            field=models.CharField(
                choices=[
                    ('general', 'Geral'),
                    ('finance', 'Finanças'),
                    ('transport', 'Transportadora'),
                    ('investments', 'Investimentos'),
                ],
                max_length=32,
            ),
        ),
    ]
