# Generated by Django 4.2.10 on 2026-03-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_tenantparameter_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account_notes',
            field=models.TextField(blank=True, verbose_name='Observações da conta'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='account_status',
            field=models.CharField(choices=[('active', 'Ativa'), ('past_due', 'Inadimplente'), ('suspended', 'Suspensa'), ('cancelled', 'Desistência/Cancelada')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da conta'),
        ),
    ]
