# Generated by Django 4.2.10 on 2026-03-07 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tenantparameter_module'),
        ('finance', '0002_transaction_current_installment_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_fixed_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='affects_balance',
            field=models.BooleanField(default=True, verbose_name='Impacta Saldo'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('debit_card', 'Cartão de Débito'), ('credit_card', 'Cartão de Crédito'), ('bank_transfer', 'Transferência'), ('other', 'Outros')], default='other', max_length=20)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('closing_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Formas de pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_month', models.DateField(verbose_name='Mês de referência')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('paid', 'Paga')], default='open', max_length=10)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.paymentmethod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_invoices', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Fatura de cartão',
                'verbose_name_plural': 'Faturas de cartão',
                'ordering': ['-reference_month', '-created_at'],
                'unique_together': {('tenant', 'payment_method', 'reference_month')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.creditcardinvoice', verbose_name='Fatura de Cartão'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.paymentmethod', verbose_name='Forma de Pagamento'),
        ),
    ]
