# Generated by Django 4.2.10 on 2026-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_default_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor padrão do lançamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_entry_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição padrão do lançamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='system_key',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Chave do sistema'),
        ),
    ]
