"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
config = AutoConfig(search_path=BASE_DIR)


def _read_env_file_value(key: str, default: str = '') -> str:
    env_file = BASE_DIR / '.env'
    if not env_file.exists():
        return default

    for raw_line in env_file.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        if k.strip() == key:
            return v.strip().strip('"').strip("'")

    return default


def _to_bool(value, default=False):
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _to_list(value, default=None):
    if value is None:
        return default or []
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [item.strip() for item in str(value).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-6-0)e5z43uavh9%5-6sw@=kgjqmjsvvbz0yew#-p#@g&k0sl#h')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

APP_ENV = config('APP_ENV', default=_read_env_file_value('APP_ENV', default='development'))
IS_PRODUCTION = APP_ENV.lower() == 'production'

ALLOWED_HOSTS = _to_list(
    config('ALLOWED_HOSTS', default=_read_env_file_value('ALLOWED_HOSTS', default='localhost,127.0.0.1')),
    default=['localhost', '127.0.0.1'],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_filters',
    
    # Local apps
    'accounts.apps.AccountsConfig',
    'finance.apps.FinanceConfig',
    'transport.apps.TransportConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_NAME = config('DB_NAME', default=_read_env_file_value('DB_NAME', default=''))
DB_USER = config('DB_USER', default=_read_env_file_value('DB_USER', default=''))
DB_PASSWORD = config('DB_PASSWORD', default=_read_env_file_value('DB_PASSWORD', default=''))
DB_HOST = config('DB_HOST', default=_read_env_file_value('DB_HOST', default=''))
DB_PORT = config('DB_PORT', default=_read_env_file_value('DB_PORT', default='5432'))
DB_SSLMODE = config('DB_SSLMODE', default=_read_env_file_value('DB_SSLMODE', default='prefer'))
DB_CONN_MAX_AGE = config(
    'DB_CONN_MAX_AGE',
    default=_read_env_file_value('DB_CONN_MAX_AGE', default='120'),
    cast=int,
)

missing_db_vars = [
    key
    for key, value in {
        'DB_NAME': DB_NAME,
        'DB_USER': DB_USER,
        'DB_PASSWORD': DB_PASSWORD,
        'DB_HOST': DB_HOST,
    }.items()
    if not value
]

if missing_db_vars:
    raise RuntimeError(
        'Configuração de banco PostgreSQL incompleta. Defina as variáveis: '
        + ', '.join(missing_db_vars)
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': DB_CONN_MAX_AGE,
        'OPTIONS': {
            'sslmode': DB_SSLMODE,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# REST Framework Configuration
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ============================================================================
# JWT Configuration
# ============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JTI_CLAIM': 'jti',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ============================================================================
# CORS Configuration
# ============================================================================

CORS_ALLOWED_ORIGINS = _to_list(
    config(
        'CORS_ALLOWED_ORIGINS',
        default=_read_env_file_value(
            'CORS_ALLOWED_ORIGINS',
            default='http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174',
        ),
    ),
)

CSRF_TRUSTED_ORIGINS = _to_list(
    config('CSRF_TRUSTED_ORIGINS', default=_read_env_file_value('CSRF_TRUSTED_ORIGINS', default='')),
)

CORS_ALLOW_CREDENTIALS = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _to_bool(
    config('SECURE_SSL_REDIRECT', default=_read_env_file_value('SECURE_SSL_REDIRECT', default='false')),
    default=False,
)
SESSION_COOKIE_SECURE = _to_bool(
    config('SESSION_COOKIE_SECURE', default=_read_env_file_value('SESSION_COOKIE_SECURE', default='false')),
    default=False,
)
CSRF_COOKIE_SECURE = _to_bool(
    config('CSRF_COOKIE_SECURE', default=_read_env_file_value('CSRF_COOKIE_SECURE', default='false')),
    default=False,
)

if IS_PRODUCTION and not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ============================================================================
# Custom User Model
# ============================================================================

AUTH_USER_MODEL = 'accounts.User'

# ============================================================================
# Authentication Backends
# ============================================================================

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================================================
# Tenant Configuration
# ============================================================================

TENANT_MODEL = 'accounts.Tenant'

# ============================================================================
# AI Assistant Configuration
# ============================================================================

GEMINI_API_KEY = config('GEMINI_API_KEY', default='') or _read_env_file_value('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-2.5-flash') or _read_env_file_value('GEMINI_MODEL', default='gemini-2.5-flash')
ASSISTANT_ENABLE_GEMINI = _to_bool(
    config('ASSISTANT_ENABLE_GEMINI', default=_read_env_file_value('ASSISTANT_ENABLE_GEMINI', default='false')),
    default=False,
)
ASSISTANT_CHAT_ENABLED = _to_bool(
    config('ASSISTANT_CHAT_ENABLED', default=_read_env_file_value('ASSISTANT_CHAT_ENABLED', default='false')),
    default=False,
)
